return {
  require 'plugins.which-key',
  require 'plugins.telescope',
  require 'plugins.nvim-dap',
  require 'plugins.nvim-lspconfig',
  require 'plugins.neo-tree',
  require 'plugins.lazygit',
  require 'plugins.mini',
  require 'plugins.nvim-treesitter',
  require 'plugins.todo-comments',
  require 'plugins.windsurf',
  require 'plugins.conform',
  require 'plugins.gitsigns',
  require 'plugins.indent-blankline',
  require 'plugins.lazydev',
  require 'plugins.nvim-autopairs',
  require 'plugins.todo-comments',
  require 'plugins.tokyonight',
  require 'plugins.comment',
  require 'plugins.lualine',
  require 'plugins.toggleterm',
  require 'plugins.nvim-cmp',
  -- Add more here
}
